# Numpy:
Numpy is an open sourse library that is used for scientific calculation.

# Why numpy is better than list ?
1) Numpy(Homogeneous datatype) , List(Hetrogeneous datatype)
2) Numpy(Less time consumption) , List(more time consumption)
3) Numpy(Less memory consumption) , List(more memory consumption)

In [5]:
!pip install numpy


[notice] A new release of pip is available: 23.0.1 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [3]:
import numpy as np

In [7]:
a = [1,45,89,90]
type(a)

list

In [8]:
b=np.array(a)
b

array([ 1, 45, 89, 90])

In [9]:
c = [[1,2,3] , [4,5,6] , [7,8,9]]
d=np.array(c)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
print("Total rows and columns:" , d.shape)  #Shape = n(rows) , n(columns)
print("Total elements:" , d.size)   # Size = n(rows)*n(columns)
print("Total Dimension:" , d.ndim)

Total rows and columns: (3, 3)
Total elements: 9
Total Dimension: 2


In [11]:
b.ndim

1

# User defined array:

In [12]:
a = []
size = int(input("Enter size:"))
for i in range(size):
    val=int(input("Enter values:"))
    a.append(val)
# Print(a)
b = np.array(a)
b

Enter size: 3
Enter values: 5
Enter values: 6
Enter values: 7


array([5, 6, 7])

In [13]:
type(b)

numpy.ndarray

In [14]:
a = [1,2,3]
a*3

[1, 2, 3, 1, 2, 3, 1, 2, 3]

In [16]:
a = np.array([1,2,3])
a*3

array([3, 6, 9])

# Pre-defined functions of numpy

In [17]:
# 1) zeros() ---> It will create an array in which all values will be 0.

In [18]:
a = np.zeros(3)
a

array([0., 0., 0.])

In [21]:
a=np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
# 2) ones() ---> It will create an array in which all the values will be 1.

In [23]:
a = np.ones(4)
a

array([1., 1., 1., 1.])

In [24]:
a=np.ones((4,5))
a

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [25]:
# 3) eye(): It will create an array in which diagonal positional elements will be 1 
# and rest are zero.

In [26]:
a = np.eye(5)  # n(rows) = n(columns)  --> Symmetric matriz
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [27]:
a = np.eye(3,4)   # n(rows)!=n(columns)  ---> Asymetric matrix
a

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [28]:
a.ndim

2

In [29]:
# 4) diag() --> It will create an array that will set diagonal positional custom values.

In [30]:
a = np.diag([1,22,333,4444])
a

array([[   1,    0,    0,    0],
       [   0,   22,    0,    0],
       [   0,    0,  333,    0],
       [   0,    0,    0, 4444]])

# Random Module:

In [1]:
# (a) Randint() ---> It will generate random values based on fix criteria
# np.random.randint(min_range , max_range , total_numbers)

In [4]:
a = np.random.randint(1,10,3)
a

array([5, 9, 9], dtype=int32)

In [5]:
# b) Rand() ---> It will generate random numbers from 0 to 1.

In [6]:
a = np.random.rand(5)
a

array([0.53062367, 0.81667747, 0.26799985, 0.29033232, 0.2075254 ])

In [7]:
# c) seed() ---> It will fix our random generated data.

In [8]:
np.random.seed(30)
a = np.random.randint(1,10,3)
a

array([6, 6, 5], dtype=int32)

# View vs copy

In [9]:
a = np.array([10,20,30,40,50,60,70,80])  # view method
b = a[3:6]
b[:] = 0
b
a

array([10, 20, 30,  0,  0,  0, 70, 80])

In [10]:
a = np.array([10,20,30,40,50,60,70,80])  # copy method
b = a[3:6]
b[:] = 0
b
a

array([10, 20, 30,  0,  0,  0, 70, 80])

# Reshaping the array:

In [11]:
# n(rows) * n(columns) = n(Total Elements)

In [16]:
a = np.random.randint(1,50,12)

In [17]:
a.reshape(2,6)

array([[13, 24,  3, 18, 47,  4],
       [42,  8,  2, 46, 36, 19]], dtype=int32)

In [18]:
a.reshape(6,2)

array([[13, 24],
       [ 3, 18],
       [47,  4],
       [42,  8],
       [ 2, 46],
       [36, 19]], dtype=int32)

In [19]:
a.reshape(3,4)

array([[13, 24,  3, 18],
       [47,  4, 42,  8],
       [ 2, 46, 36, 19]], dtype=int32)

In [20]:
a.reshape(4,3)

array([[13, 24,  3],
       [18, 47,  4],
       [42,  8,  2],
       [46, 36, 19]], dtype=int32)

# Conditional selection in Numpy:

In [23]:
a = np.arange(1,15)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
a>10

array([False, False, False, False, False, False, False, False, False,
       False,  True,  True,  True,  True])

In [26]:
b = a>10
a[b]

array([11, 12, 13, 14])

In [29]:
a[a%2==0]

array([2, 4])

In [30]:
a = np.array([1,2,3,4])
a**2

array([ 1,  4,  9, 16])

In [31]:
a**3

array([ 1,  8, 27, 64])

In [32]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [33]:
np.cos(a)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

In [34]:
np.sqrt(a)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [36]:
a = np.array([1,2,3,4]).reshape(2,2)
a

array([[1, 2],
       [3, 4]])

In [37]:
b = np.array([5,6,7,8]).reshape(2,2)
b

array([[5, 6],
       [7, 8]])

In [38]:
a*b

array([[ 5, 12],
       [21, 32]])

In [39]:
a+b

array([[ 6,  8],
       [10, 12]])

In [40]:
a.dot(b)   # for matrix multiplication

array([[19, 22],
       [43, 50]])

# Unique(): It will return 3 arrays
1) Arr ---> Unique values store.
2) retuen_index = True ---> In which indexing we have unique values.
3) return_counts = True ---> Frequency of each element.

In [41]:
a = np.array([1,2,2,3,3,3,3,1,1,2,7,8,4])
a

array([1, 2, 2, 3, 3, 3, 3, 1, 1, 2, 7, 8, 4])

In [42]:
np.unique(a , return_index = True , return_counts = True)

(array([1, 2, 3, 4, 7, 8]),
 array([ 0,  1,  3, 12, 10, 11]),
 array([3, 3, 4, 1, 1, 1]))